[build]
  # This should be "build" for a React project, not "dist"
  publish = "build"
  functions = "functions"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
